name: fedscgen
channels:
  - r
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _r-mutex=1.0.0=anacondar_1
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - binutils_impl_linux-64=2.38=h2a08ee3_1
  - binutils_linux-64=2.38.0=hc2dff05_0
  - blas=1.0=openblas
  - bwidget=1.9.11=1
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.0=h5eee18b_0
  - ca-certificates=2023.12.12=h06a4308_0
  - cairo=1.16.0=hb05425b_5
  - curl=7.88.1=h5eee18b_1
  - expat=2.4.9=h6a678d5_0
  - fontconfig=2.14.1=h4c34cd2_2
  - freetype=2.12.1=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_0
  - gfortran_impl_linux-64=11.2.0=h1234567_1
  - gfortran_linux-64=11.2.0=hc2dff05_0
  - glib=2.69.1=he621ea3_2
  - graphite2=1.3.14=h295c915_1
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_0
  - harfbuzz=4.3.0=hf52aaf7_1
  - icu=58.2=he6710b0_3
  - jpeg=9e=h5eee18b_1
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcurl=7.88.1=h251f7ec_1
  - libdeflate=1.17=h5eee18b_0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libidn2=2.3.4=h5eee18b_0
  - libnghttp2=1.52.0=h2d74bed_1
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.39=h5eee18b_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.10.3=hcbfbd50_0
  - lz4-c=1.9.4=h6a678d5_0
  - make=4.2.1=h1bed415_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.12=h7f8727e_0
  - pango=1.50.7=h05da053_0
  - pcre=8.45=h295c915_0
  - pcre2=10.37=he7ceb23_1
  - pip=23.1.2=py310h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - python=3.10.12=h955ad1f_0
  - r-askpass=1.1=r42h76d94ec_0
  - r-base=4.2.0=h1ae530e_0
  - r-brew=1.0_7=r42h6115d3f_0
  - r-brio=1.1.3=r42h76d94ec_0
  - r-cachem=1.0.6=r42h76d94ec_0
  - r-callr=3.7.0=r42h6115d3f_0
  - r-cli=3.3.0=r42h884c59f_0
  - r-clipr=0.8.0=r42h6115d3f_0
  - r-colorspace=2.0_3=r42h76d94ec_0
  - r-commonmark=1.8.0=r42h76d94ec_0
  - r-cpp11=0.4.2=r42h6115d3f_0
  - r-crayon=1.5.1=r42h6115d3f_0
  - r-credentials=1.3.2=r42h142f84f_0
  - r-curl=4.3.2=r42h76d94ec_0
  - r-desc=1.4.1=r42h6115d3f_0
  - r-devtools=2.4.3=r42h6115d3f_0
  - r-diffobj=0.3.5=r42h76d94ec_0
  - r-digest=0.6.29=r42h884c59f_0
  - r-ellipsis=0.3.2=r42h76d94ec_0
  - r-essentials=0.1.0=r42h76d94ec_0
  - r-evaluate=0.15=r42h6115d3f_0
  - r-fansi=1.0.3=r42h76d94ec_0
  - r-farver=2.1.0=r42h884c59f_0
  - r-fastmap=1.1.0=r42h884c59f_0
  - r-fs=1.5.2=r42h884c59f_0
  - r-gert=1.6.0=r42h76d94ec_0
  - r-ggplot2=3.3.6=r42h6115d3f_0
  - r-gh=1.3.0=r42h142f84f_0
  - r-gitcreds=0.1.1=r42h6115d3f_0
  - r-glue=1.6.2=r42h76d94ec_0
  - r-gtable=0.3.0=r42h6115d3f_0
  - r-highr=0.9=r42h6115d3f_0
  - r-httr=1.4.3=r42h6115d3f_0
  - r-ini=0.3.1=r42h142f84f_0
  - r-isoband=0.2.5=r42h884c59f_0
  - r-jsonlite=1.8.0=r42h76d94ec_0
  - r-knitr=1.39=r42h6115d3f_0
  - r-labeling=0.4.2=r42h6115d3f_0
  - r-lattice=0.20_45=r42h76d94ec_0
  - r-lifecycle=1.0.1=r42h142f84f_0
  - r-magrittr=2.0.3=r42h76d94ec_0
  - r-mass=7.3_57=r42h76d94ec_0
  - r-matrix=1.4_1=r42h76d94ec_0
  - r-memoise=2.0.1=r42h6115d3f_0
  - r-mgcv=1.8_40=r42h76d94ec_0
  - r-mime=0.12=r42h76d94ec_0
  - r-munsell=0.5.0=r42h6115d3f_0
  - r-nlme=3.1_157=r42h640688f_0
  - r-openssl=2.0.2=r42h76d94ec_0
  - r-pillar=1.7.0=r42h6115d3f_0
  - r-pkgbuild=1.3.1=r42h142f84f_0
  - r-pkgconfig=2.0.3=r42h6115d3f_0
  - r-pkgload=1.2.4=r42h142f84f_0
  - r-praise=1.0.0=r42h6115d3f_4
  - r-prettyunits=1.1.1=r42h142f84f_0
  - r-processx=3.5.3=r42h76d94ec_0
  - r-ps=1.7.0=r42h76d94ec_0
  - r-purrr=0.3.4=r42h76d94ec_0
  - r-r6=2.5.1=r42h6115d3f_0
  - r-rappdirs=0.3.3=r42h76d94ec_0
  - r-rcmdcheck=1.4.0=r42h142f84f_0
  - r-rcolorbrewer=1.1_3=r42h6115d3f_0
  - r-rematch2=2.1.2=r42h142f84f_0
  - r-remotes=2.4.2=r42h142f84f_0
  - r-rlang=1.0.2=r42h884c59f_0
  - r-roxygen2=7.2.0=r42h884c59f_0
  - r-rprojroot=2.0.3=r42h6115d3f_0
  - r-rstudioapi=0.13=r42h6115d3f_0
  - r-rversions=2.1.1=r42h6115d3f_0
  - r-scales=1.2.0=r42h6115d3f_0
  - r-sessioninfo=1.2.2=r42h142f84f_0
  - r-stringi=1.7.6=r42h884c59f_0
  - r-stringr=1.4.0=r42h6115d3f_0
  - r-sys=3.4=r42h76d94ec_0
  - r-testthat=3.1.4=r42h884c59f_0
  - r-tibble=3.1.7=r42h76d94ec_0
  - r-usethis=2.1.6=r42h142f84f_0
  - r-utf8=1.2.2=r42h76d94ec_0
  - r-vctrs=0.4.1=r42h884c59f_0
  - r-viridislite=0.4.0=r42h6115d3f_0
  - r-waldo=0.4.0=r42h6115d3f_0
  - r-whisker=0.4=r42h6115d3f_0
  - r-withr=2.5.0=r42h6115d3f_0
  - r-xfun=0.31=r42h76d94ec_0
  - r-xml2=1.3.3=r42h884c59f_0
  - r-xopen=1.0.0=r42h142f84f_0
  - r-yaml=2.3.5=r42h76d94ec_0
  - r-zip=2.2.0=r42h76d94ec_0
  - readline=8.2=h5eee18b_0
  - setuptools=67.8.0=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - tk=8.6.12=h1ccaba5_0
  - tktable=2.10=h14c3975_0
  - wheel=0.38.4=py310h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - numpy==1.24.4
      - scikit-learn==1.3.0
      - scikit-misc==0.3.0
      - crypten==0.4.1
      - absl-py==1.4.0
      - adjusttext==0.8
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - anndata==0.9.1
      - annoy==1.17.3
      - anyio==3.7.1
      - arrow==1.2.3
      - async-timeout==4.0.2
      - attrs==23.1.0
      - backoff==2.2.1
      - bbknn==1.3.9
      - beautifulsoup4==4.12.2
      - blessed==1.20.0
      - cachetools==5.3.1
      - certifi==2023.5.7
      - cffi==1.15.1
      - charset-normalizer==3.2.0
      - chex==0.1.7
      - click==8.1.4
      - cmake==3.26.4
      - contextlib2==21.6.0
      - contourpy==1.1.0
      - croniter==1.4.1
      - cycler==0.11.0
      - cython==3.0.0
      - dateutils==0.6.12
      - deepdiff==6.3.1
      - deprecated==1.2.14
      - dm-tree==0.1.8
      - docrep==0.3.2
      - etils==1.3.0
      - exceptiongroup==1.1.2
      - fastapi==0.100.0
      - fbpca==1.0
      - filelock==3.12.2
      - flax==0.7.0
      - fonttools==4.41.0
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - gdown==4.7.1
      - geosketch==1.2
      - google-auth==2.22.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.56.2
      - h11==0.14.0
      - h5py==3.9.0
      - idna==3.4
      - igraph==0.10.5
      - importlib-resources==6.0.0
      - inquirer==3.1.3
      - intervaltree==2.1.0
      - itsdangerous==2.1.2
      - jax==0.4.13
      - jaxlib==0.4.13
      - jinja2==3.1.2
      - joblib==1.3.1
      - kiwisolver==1.4.4
      - leidenalg==0.10.0
      - lightning==2.0.5
      - lightning-cloud==0.5.37
      - lightning-utilities==0.9.0
      - lit==16.0.6
      - llvmlite==0.40.1
      - louvain==0.8.1
      - markdown==3.4.4
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.7.2
      - matplotlib-venn==0.11.9
      - mdurl==0.1.2
      - ml-collections==0.1.1
      - ml-dtypes==0.2.0
      - mpmath==1.3.0
      - msgpack==1.0.5
      - mudata==0.2.3
      - multidict==6.0.4
      - multipledispatch==1.0.0
      - muon==0.1.5
      - mypy-extensions==1.0.0
      - natsort==8.4.0
      - nest-asyncio==1.5.6
      - networkx==3.1
      - newick==1.0.0
      - numba==0.57.1
      - numpyro==0.12.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - optax==0.1.5
      - orbax-checkpoint==0.2.7
      - ordered-set==4.1.0
      - packaging==23.1
      - pandas==1.5.3
      - patsy==0.5.3
      - pillow==10.1.0
      - protobuf==4.23.4
      - psutil==5.9.5
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pydantic==1.10.11
      - pydot==1.4.2
      - pygments==2.15.1
      - pyjwt==2.7.0
      - pynndescent==0.5.10
      - pyparsing==3.0.9
      - pypdf2==3.0.1
      - pyre-extensions==0.0.30
      - pyro-api==0.1.2
      - pyro-ppl==1.8.5
      - pysocks==1.7.1
      - python-dateutil==2.8.2
      - python-editor==1.0.4
      - python-louvain==0.16
      - python-multipart==0.0.6
      - pytorch-lightning==2.0.5
      - pytz==2023.3
      - pyupset==0.1.1.post7
      - pyyaml==6.0
      - readchar==4.0.5
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rich==13.4.2
      - rpy2==3.5.13
      - rsa==4.9
      - scanorama==1.7
      - scanpy==1.9.3
      - scarches==0.5.9
      - scgen==2.1.0
      - schpl==1.0.3
      - scib==1.1.3
      - scipy==1.11.1
      - scvi-tools==1.0.2
      - seaborn==0.12.2
      - session-info==1.0.0
      - six==1.16.0
      - sniffio==1.3.0
      - sortedcontainers==2.4.0
      - soupsieve==2.4.1
      - sparse==0.14.0
      - starlette==0.27.0
      - starsessions==1.3.0
      - statsmodels==0.14.0
      - stdlib-list==0.9.0
      - sympy==1.12
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.1
      - tensorstore==0.1.40
      - texttable==1.6.7
      - threadpoolctl==3.1.0
      - toolz==0.12.0
      - torch==2.0.1
      - torcheval==0.0.6
      - torchmetrics==1.0.0
      - torchtnt==0.1.0
      - tqdm==4.65.0
      - traitlets==5.9.0
      - triton==2.0.0
      - typing-extensions==4.7.1
      - typing-inspect==0.9.0
      - tzdata==2023.3
      - tzlocal==5.0.1
      - umap-learn==0.5.3
      - upsetplot==0.8.0
      - urllib3==1.26.16
      - uvicorn==0.22.0
      - wcwidth==0.2.6
      - websocket-client==1.6.1
      - websockets==11.0.3
      - werkzeug==2.3.6
      - wget==3.2
      - wrapt==1.15.0
      - xarray==2023.6.0
      - yarl==1.9.2
      - zipp==3.16.1
prefix: ~/anaconda3/envs/sc
